### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [dansteryoo/aa_final_project#2]
- [ ] Users: 
     - [ ] What is status? 
     - [ ] Needs a first name and last name
- [x] Hosts are users that own listings 
- [x] Add in indexes 
- [x] Ratings need to hold rating information - what was the rating out of 5? 
- [x] Listings do not need a review_id 
- [x] Lets talk about how to divide your location and listing information early next week 
- [x] Lets combine rating and reviews

**Comment by dansteryoo** [comment]
done!
